### ISSUE TITLE
The game mode change was cancelled!

### ISSUE THREAD

**Issue by Diamondsplox** [sunkid/WorldModes#3]
Hi. I am using WorldModes v2.0 with PEX and i gave the Admins 'worldmodes.set.self', but when they try "/gm creative" it says "The game mode change was cancelled!". What does this mean? Pleas help!

**Comment by sunkid** [comment]
You need to set worldmodes.mode.creative for this world as well. If you have any other plugins enforcing game modes, those could also cause the same message as it is issued by CraftBukkit and not the WorldModes plugin.

**Comment by sunkid** [comment]
Can I close this issue or are you still experiencing problems?

**Comment by Diamondsplox** [comment]
Yes. This fixed it. Thank you. You can close it.
