### ISSUE TITLE
Could not pass event PLAYER_GAME_MODE_CHANGE

### ISSUE THREAD

**Issue by fromalexx** [sunkid/WorldModes#4]
When a user changes game modes it displays this error in the console:

SEVERE Could not pass event PLAYER_GAME_MODE_CHANGE to WorldModes

Here is the full error:

22.10 05:36:27 [Server] INFO    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
22.10 05:36:27 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
22.10 05:36:27 [Server] INFO    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:441)
22.10 05:36:27 [Server] INFO    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
22.10 05:36:27 [Server] INFO    at com.onarandombox.MultiverseCore.listeners.MVPlayerListener$HandleGameMode.run(MVPlayerListener.java:221)
22.10 05:36:27 [Server] INFO    at org.bukkit.craftbukkit.entity.CraftPlayer.setGameMode(CraftPlayer.java:468)
22.10 05:36:27 [Server] INFO    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
22.10 05:36:27 [Server] INFO    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
22.10 05:36:27 [Server] INFO    at org.bukkit.plugin.java.JavaPluginLoader$28.execute(JavaPluginLoader.java:449)
22.10 05:36:27 [Server] INFO    at com.iminurnetz.bukkit.plugin.worldmodes.GameModeChangePlayerListener.onPlayerGameModeChange(GameModeChangePlayerListener.java:60)
22.10 05:36:27 [Server] INFO    at com.iminurnetz.bukkit.plugin.worldmodes.GameModeChangePlayerListener.restoreInventory(GameModeChangePlayerListener.java:118)
22.10 05:36:27 [Server] INFO    at com.iminurnetz.bukkit.plugin.worldmodes.PersistedInventory.revertInventory(PersistedInventory.java:77)
22.10 05:36:27 [Server] INFO java.lang.NullPointerException
22.10 05:36:27 [Server] SEVERE Could not pass event PLAYER_GAME_MODE_CHANGE to WorldModes

**Comment by sunkid** [comment]
It is possible that you are not using the latest version of the plugin. Can you please [download version 2.3](http://dev.bukkit.org/server-mods/worldmodes/files/4-v2-3/) as this problem was addressed in 1.9, I believe.
