### ISSUE TITLE
Game mode will not change

### ISSUE THREAD

**Issue by ArcanoxDragon** [sunkid/WorldModes#6]
I have a player with worldmodes.modes.\* and they can't be changed back from creative. They don't have any autoset permissions, it just says "The game mode change was cancelled." I can't get anything to work. Not even I can change it.

**Comment by sunkid** [comment]
Do you use any other plugins that may be enforcing game modes? Can you post your permission configuration, please? Also, what permission plugin are you using?

**Comment by ArcanoxDragon** [comment]
I'm using Permissions. All of the other users of the same rank can change. Just not this one user. I uninstalled all GameMode plugins except this one. My permissions for world: http://pastebin.com/GpVmU14N

**Comment by sunkid** [comment]
The fact that other players with the same rank can change would indicate that this player has a player-specific permission set. Can you please check if the player actually has the worldmodes.modes.survival permission in that world. I believe the command is something like

```
/pr <username> w:<world> has worldmodes.modes.survival
```

You can also check the Permissions plugin folder and its subfolders to make sure that the player doesn't have special permissions set.

**Comment by ArcanoxDragon** [comment]
It was an error in permissions. It should be "worldmodes.mode._", not "worldmodes.modes._".

**Comment by sunkid** [comment]
ahhh... I should have caught that. Glad you solved it.
