### ISSUE TITLE
If autoset permission is given to a user, autoset that mode

### ISSUE THREAD

**Issue by contre** [sunkid/WorldModes#7]
A small feature request, not sure if it is possible since there are many different permission plugins but it would be helpful that if I give a player an autoset permission that they get set to that mode.

It would save me the hassle of typing out the gm command.

**Comment by sunkid** [comment]
Does the worldmodes.autoset.{creative,survival} permission not work for you? Any player with either permission should be automatically set to that mode.

**Comment by contre** [comment]
It does not change them when I give them the permission and they're stilled logged in.

**Comment by sunkid** [comment]
Yes, that is the intended functionality. The permission is only enforced when the player changes worlds or logs in. Enforcing it when the permission is assigned is not feasible as there are no hooks for a permission change event.

**Comment by contre** [comment]
That is what I thought. Just wanted to confirm.
