### ISSUE TITLE
Creative players can access furnaces

### ISSUE THREAD

**Issue by contre** [sunkid/WorldModes#8]
I'm not sure if this is intended or not, but creative players can access furnaces even when blocked from accessing chests and dispensers.

Line 81 of WMPlayerListener.java
if (block.getType() == Material.CHEST || block.getType() == Material.DISPENSER) {

**Comment by sunkid** [comment]
Yes, that is intended! Cutting them off from furnaces seems to restrictive on game play IMHO.

**Comment by contre** [comment]
I figured since they had access to every item, they wouldn't need to smelt things. Fair enough if it was intended.
